rx-elf

01_new_batch を実行した結果, 最後の確認まで期待通り動作しているっぽい.
しかし以下の結果になる.

% rx-elf-gcc -g -o 00_batch.verify.elf 00_batch.verify.c
during RTL pass: dwarf2
00_batch.verify.c: 関数 ‘main’ 内:
00_batch.verify.c:7:1: コンパイラ内部エラー: dwarf2out_frame_debug_adjust_cfa 内、位置 dwarf2cfi.c:1189
    7 | }
      | ^
0x816697a dwarf2out_frame_debug_adjust_cfa
	../.././gcc/dwarf2cfi.c:1189
0x816697a dwarf2out_frame_debug
	../.././gcc/dwarf2cfi.c:2098
0x8315f16 scan_insn_after
	../.././gcc/dwarf2cfi.c:2547
0x8315f16 scan_trace
	../.././gcc/dwarf2cfi.c:2714
0x8316441 create_cfi_notes
	../.././gcc/dwarf2cfi.c:2758
0x8316441 execute_dwarf2_frame
	../.././gcc/dwarf2cfi.c:3122
0x8316441 execute
	../.././gcc/dwarf2cfi.c:3610
Please submit a full bug report,
with preprocessed source if appropriate.
Please include the complete backtrace with any bug report.
See <https://gcc.gnu.org/bugs/> for instructions.
> rx-elf-gcc -g -o 00_batch.verify.elf 00_batch.verify.c
%
